src/agata/apps/magazzino/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import *
from django.contrib import admin


urlpatterns = patterns('',
                       ############################################################################
                       ##########     U R L   P R O T E T T E   D A   L O G I N          ##########
                       ############################################################################
                       url('operazione_completata', 'agata.apps.magazzino.views.operazione_completata', name="operazione_completata"),
                       url('operazioni/ubicazioni/(?P<tipo>(deposito|prelievo))', 'agata.apps.magazzino.views.operazioni_ubicazioni', name="operazione_magazzino_ubicazioni"),
                       url('operazioni/(?P<tipo>(deposito|prelievo))/(?P<id_operazione>\d+)', 'agata.apps.magazzino.views.operazioni', name="operazione_magazzino"),
                       url('operazioni/(?P<tipo>(deposito|prelievo))/(?P<tutto>.*)', 'agata.apps.magazzino.views.operazioni', {'manuale':True}, name="operazione_magazzino"),
                       url('vedi_ordine/(?P<id_ordine>\d+)', 'agata.apps.magazzino.views.vedi_ordine', name="magazzino_vedi_ordine"),
                       url('apri_ordine/(?P<id_ordine>\d+)', 'agata.apps.magazzino.views.apri_ordine', name="magazzino_apri_ordine"),

                       url('storico_articoli_download/(?P<codice>.*)', 'agata.apps.magazzino.views.storico_articoli_download', name="agata.apps.magazzino_storico_articoli_download"),
                       url('storico_articoli', 'agata.apps.magazzino.views.storico_articoli', name="magazzino_storico_articoli"),
                       url('stampa_etichette', 'agata.apps.magazzino.views.stampa_etichette', name="magazzino_stampa_etichette"),
)

src/agata/apps/magazzino/models.py
#-*- coding: utf-8 -*-

import re, os, datetime

from django.db import models
import agata.apps.articoli.models as articoli_db
import agata.apps.anagrafiche.models as anagrafiche_db
from django.forms import ModelForm
from django import forms
from django.conf import settings
from django.utils.safestring import mark_safe



class Magazzino(models.Model):
    nome = models.CharField(max_length=256, unique=True)

    class Meta:
        verbose_name_plural = 'magazzini'

    def __unicode__(self):
        return self.nome

    def giacenza_(instance):
        totale = 0
        for g in instance.giacenza_set.all():
            totale += g.quantita
        return u'%d pezzi - <a href="/admin/magazzino/giacenza/?magazzino__id__exact=%d">Vedi dettaglio</a>' % (totale, instance.id)
    giacenza_.allow_tags = True


class Giacenza(models.Model):
    magazzino = models.ForeignKey(Magazzino)
    articolo = models.ForeignKey(articoli_db.Articolo)
    quantita = models.IntegerField()
    ubicazione = models.CharField(max_length=5, null=True, blank=True)
    in_prelievo = models.IntegerField(default=0)
    in_deposito = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'giacenze'

    def __unicode__(self):
        return self.articolo.codice

    def codice_ean(instance):
        return instance.articolo.codice_ean
    codice_ean.allow_tags = True
    codice_ean.admin_order_field = 'articolo__codice_ean'

    def produttore(instance):
        return instance.articolo.produttore
    produttore.allow_tags = True
    produttore.admin_order_field = 'articolo__produttore'


STATI_OPERAZIONI = (
    ('Inserito', 'Inserito'),
    ('In Corso', 'In Corso'),
    ('Annullata', 'Annullata'),
    ('Completata', 'Completata'),
)

TIPI_OPERAZIONI = (
    ('prelievo', 'prelievo'),
    ('deposito', 'deposito'),
    ('trasferimento', 'trasferimento')
    )

class OperazioneMagazzino(models.Model):
    tipo = models.CharField(max_length=64, choices=TIPI_OPERAZIONI)
    magazzino_ingresso = models.ForeignKey(Magazzino, null=True, blank=True, related_name='magazzino_da', verbose_name="Magazzino ingresso")
    magazzino_uscita = models.ForeignKey(Magazzino, null=True, blank=True, verbose_name='magazzino uscita' )
    letture = models.TextField()
    richiesta = models.TextField(null=True, blank=True) # Questo campo viene popolato con i barcode della richiesta originale (se esiste) e usato per fare le verifiche
    ts_operazione = models.DateTimeField(auto_now_add=True)
    stato = models.CharField(max_length=64, choices=STATI_OPERAZIONI)
    note = models.TextField(null=True, blank=True)
    pezzi = models.IntegerField()

    class Meta:
        verbose_name_plural = 'storico operazioni'

    def __unicode__(self):
        return u'%s' % (self.tipo)

    def verifica(self):
        # Questa funzione dovrà restituire il risultato del confronto tra le letture e la richiesta
        pass

class OperazioneMagazzinoForm(ModelForm):
    class Meta:
        model = OperazioneMagazzino
        exclude = ['stato', 'ts_operazione', 'tipo', 'pezzi', 'richiesta']


class GiacenzaForm(ModelForm):
    class Meta:
        model = Giacenza
        exclude = ['articolo', 'in_prelievo', 'in_deposito']

    codice_articolo = forms.CharField()
    note = forms.CharField(required=False)

    def clean_codice_articolo(self):
        # Verifico l'esistenza dell'articolo
        codice = self.cleaned_data['codice_articolo']
        try:
            test = articoli_db.Articolo.objects.get(codice=codice)
        except  articoli_db.Articolo.DoesNotExist:
            raise forms.ValidationError('Articolo non presente in anagrafica')
        return codice



class Ordine(models.Model):
    """ Questo modello serve a contenere le richieste di prelievo / deposito che vengono inserite.
        A seguito della verifica dell'operazione, si procede con la creazione della relativa operazione di magazzino
    """

    def upload_file(instance, filename):
        # ignoro il filename, lo rinomino
        anno = datetime.datetime.now().year
        rag_sociale = re.sub(r'\W', '_', instance.societa.ragione_sociale)
        filename = os.path.basename(filename)
        filename, ext = os.path.splitext(filename)
        filename = re.sub(r'\W', '_', filename)
        return u'ordini/import/%d/%s/%s%s' % (anno, rag_sociale, filename, ext)

    # CAMPI NOSTRI
    ts_ordine = models.DateTimeField(auto_now=True)
    societa = models.ForeignKey(anagrafiche_db.Societa)
    tipo = models.CharField(max_length=64, choices=TIPI_OPERAZIONI)
    stato = models.CharField(max_length=64, choices=STATI_OPERAZIONI)
    magazzino_ingresso = models.ForeignKey(Magazzino, null=True, blank=True, related_name='magazzino_ingresso', verbose_name="Magazzino ingresso")
    magazzino_uscita = models.ForeignKey(Magazzino, null=True, blank=True, related_name='magazzino_uscita', verbose_name='magazzino uscita' )
    richiesta = models.TextField()
    note = models.TextField(null=True, blank=True)
    operazione = models.OneToOneField(OperazioneMagazzino, null=True, blank=True)
    pezzi = models.IntegerField()
    file_originale = models.FileField(max_length=1024, null=True, blank=True, upload_to=upload_file)
    richiesta_modificata = models.BooleanField(default=False)

    # CAMPI DI QUELLO CHE GENERA L'ORDINE
    numero_documento = models.CharField(max_length=64, null=True, blank=True)
    data_documento = models.DateField(null=True, blank=True)
    codice_cliente_fornitore = models.CharField(max_length=128, null=True, blank=True)
    ragione_sociale_anagrafica = models.CharField(max_length=128, null=True, blank=True)

    note_logistica = models.TextField(null=True, blank=True)
    peso_lordo = models.FloatField(null=True, blank=True)
    peso_netto = models.FloatField(null=True, blank=True)
    numero_colli = models.IntegerField(null=True, blank=True)
    esportato = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Ordini'

    def __unicode__(self):
        return u'%s' % (self.numero_documento)

    def stampa_lista(self):
        return mark_safe('<a href="/magazzino/vedi_ordine/%d" target="_blank">Stampa lista</a>' % self.id)

    stampa_lista.allow_tags = True
    stampa_lista.short_description = 'Stampa lista'


    def apri_ordine(self):
        if self.stato not in ['Annullata','Completata']:
            return mark_safe('<a href="/magazzino/apri_ordine/%d" target="_blank">Apri</a>' % self.id)
        else:
            return mark_safe('<a href="/magazzino/apri_ordine/%d" target="_blank">Vedi</a>' % self.id)

    apri_ordine.allow_tags = True
    apri_ordine.short_description = 'Apri ordine'

    def richiesta_hr(self):
        import custom.soedis.models as soedis_db
        import views
        from views import parse_barcodes_con_ubicazioni
        retval = []
        if self.operazione and self.richiesta_modificata:
            letture_pulite = parse_barcodes_con_ubicazioni(self.operazione.letture)
        else:
            letture_pulite = parse_barcodes_con_ubicazioni(self.richiesta)

        print 'letture_pulite', letture_pulite

        for k, dati in letture_pulite.iteritems():
            qta = dati['tot']
            ubicazioni = dati['ubicazioni']
            try:
                test = articoli_db.Articolo.objects.get(codice=k)
            except:
                print k
            test = articoli_db.Articolo.objects.filter(codice_ean=k)
            try:
                test = articoli_db.Articolo.objects.get(codice_ean=k)
            except:
                test = articoli_db.Articolo.objects.get(codice=k)

            dato = {
                'articolo': test,
                'quantita': qta,
                'ubicazioni': ubicazioni
                }
            retval.append(dato)
        return retval


class OrdineForm(ModelForm):
    class Meta:
        model = Ordine
        exclude = ['ts_ordine', 'societa', 'stato', 'magazzino_ingresso', 'magazzino_uscita', 'richiesta', 'operazione', 'pezzi', 'numero_documento', 'data_documento', 'codice_cliente_fornitore', 'ragione_sociale_anagrafica' ]

src/agata/apps/magazzino/templates/magazzino/base_magazzino.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
     &rsaquo; <a href="/admin/magazzino/">Magazzino</a>
    </div>
<style>
  #legenda {
    position: fixed;
    top: 150px;
    right: 50px;
  }

  .tab_magazzino_ok  {
    background: #a0ffa0;;
  }
  .tab_magazzino_unknown  {
    background: #B4045F;
  }
  .tab_magazzino_some  {
    background: #FFFC00;
  }
  .tab_magazzino_more {
    background-color: cyan;
  }
  .tab_magazzino_missing {
    background-color: #FF9966;
  }
  .tab_magazzino_not_requested {
    background-color: #eF80f0;
  }
  .tab_magazzino_missing_giacenza {
    background-color: #C0C0C0;
  }

  p.error_msg {
    border: 2px solid red;
    padding: 10px;
    font-weight: bold;
    font-size: 150%;
    width:100%; 
  }

  .right_align {
    text-align:right; 
  }

  textarea {
    height: 50px;
  }

  .tabella td,
  .tabella th {
  font-size: 120%;
  padding:5px;
      border: 1px solid white;

  }


  p.err {
    background: #FF9966;
    padding: 10px;
    font-weight: bold;
    font-size: 150%;
    width: 800px;; 
  }

  p.ok  {
    background: #a0ffa0;
    padding: 10px;
    font-weight: bold;
    font-size: 150%;
    width: 800px; 
  }

</style>
{% endblock %}

src/agata/apps/magazzino/templates/magazzino/dettaglio_ordine.html
<html>
<head>
<style>
  th { text-align: left; }
  th, td {
    border: 1px solid black; 
    padding: 10px;
  }
</style>
</head>
<body>
  <h1>{{ordine.societa}} {{ordine.tipo|capfirst}} del {{ordine.ts_ordine|date:"d m Y"}}</h1>  
  <h2>{{ordine.ragione_sociale_anagrafica}} - numero documento {{ordine.numero_documento}}</h2>
  <table class="tabella">
    <tr>
      <th>Produttore</th>
      <th>Barcode</th>
      <th>Codice Articolo</th>
      <th>Descrizione</th>
      <th>Quantità Richiesta</th>
      <th>Ubicazione</th>
      {% if ordine.tipo == 'prelievo' and ordine.stato == 'Inserito' %}
      <th>Ubicazioni contenenti l'articolo<br/>(Ubicazione: Quantità)</th>
      {% endif %}
      {% if ordine.societa.id == settings.ID_PRODUTTORE_SOEDIS and ordine.tipo == 'deposito' %}
      <!--th>Barcode Master Carton</th>
      <th>Quantità per Master Carton</th-->
      {% endif %}
      
    </tr>
    {% for v in ordine.richiesta_hr %}
    <tr>
      <td>{{v.articolo.produttore}}</td>
      <td>{{v.articolo.codice_ean}}</td>
      <td>{{v.articolo.codice}}</td>
      <td>{{v.articolo.descrizione}}</td>
      <td class="right_align">{{v.quantita}}</td>
      <td class="right_align">{% if v.ubicazione %}{{v.ubicazione}}{% endif %}</td>
      {% if ordine.tipo == 'prelievo' and ordine.stato == 'Inserito' %}
      <td class="right_align">
	{% for g in v.articolo.giacenze %}
	{% if g.ubicazione %}
	{{g.ubicazione}}: {{g.quantita}}
	{% else %}
	SENZA NOME: {{g.quantita}}
	{% endif %}
	{% endfor %}
      </td>
      {% endif %}
      {% if ordine.societa.id == settings.ID_PRODUTTORE_SOEDIS and ordine.tipo == 'deposito' %}
      <!--td>{{v.articolo.soedis_articolo_related.barcode_master_carton}}</td>
      <td>{{v.articolo.soedis_articolo_related.quantita_box_per_master_carton}}</td-->
      {% endif %}
    </tr>
    {% endfor %}

  <table>

  {% if ordine.note %}<p><strong>Note del cliente: </strong>{{ordine.note}}</p>{% endif %}


</body>
</html>

src/agata/apps/magazzino/templates/magazzino/operazione_completata.html
{% extends "magazzino/base_magazzino.html" %}


{% block content %}
<h1>Operazione completata</h1>
<p>Torna al <a href="/admin/magazzino/">magazzino</a>
</p>
{% endblock %}

src/agata/apps/magazzino/templates/magazzino/operazione_magazzino.html
{% extends "magazzino/base_magazzino.html" %}


{% block content %}
<script>
function modificaOrdine() {
if (confirm('Sicuro di inviare l\'ordine modificato?')) {
    $('#modifica_richiesta').val('TRUE');
    $('#profilo').submit();
  }
}
</script>
<style>
textarea {
         height: 300px;
}
</style>
<h1>{{tipo|capfirst}} - {{operazione.stato}}</h1>
{% if not completata %}
<div>
  <form action="{% url 'operazione_magazzino' tipo id_operazione %}" method="post" enctype="multipart/form-data" style="width:385px;" id="profilo">{% csrf_token %}
    <table>
      {% if manuale %}
      <tr><td><label for="id_cliente">Cliente: &nbsp;&nbsp;&nbsp;&nbsp;</label><select name="cliente" id="cliente">
	{% for c in clienti %}
	<option value="{{c.id}}" {%if id_cliente == c.id %}selected="selected"{% endif %}>{{c.ragione_sociale}}</option>
	{% endfor %}
      </select></td></tr>
      {% endif %}
      <tr>
        <td>
          {{form.magazzino_uscita.errors}}
          <label for="id_magazzino">Magazzino Uscita:</label>
          {{form.magazzino_uscita}}
        </td>
        <td>
          {{form.magazzino_ingresso.errors}}
          <label for="id_magazzino_da">Magazzino Ingresso:</label>
          {{form.magazzino_ingresso}}
        </td>
      </tr>
      <tr>
        <td>
          {{form.letture.errors}}
          <label for="id_letture">Letture:</label>
          {{form.letture}}
        </td>
        <td>
          {{form.note.errors}}
          <label for="id_note">Note:</label>
          {{form.note}}
        </td>
      </tr>
    </table>

  {% if lettura_ok %}
    <input type="submit" value="Completa {{tipo}}" />
    <input type="hidden" value="{{lettura_ok}}" name="completa"/>
  {% else %}
    <input type="submit" value="Verifica {{tipo}}" />
    {% if tot_pezzi > 0 %}
    <input type="button" value="Completa {{tipo}} con modifica" style="float:right; background:red;color:white;" onclick="modificaOrdine();"/>
    <input type="hidden" value="FALSE" name="modifica_richiesta" id="modifica_richiesta"/>
    {% endif %}
  {% endif %}

  </form>

{% endif %}
<table cellspacing="0" cellpadding="3" id="legenda" class="tabella">
  <tbody>
    <tr>
      <th colspan="4"><h1>Riepilogo lettura</h1></th>
    </tr>

    <tr>
      <th class="left_align titolo_dati">Colli</th>
      <td class="right_align cella_dati"></td>
      <th class="left_align titolo_dati">Articoli</th>
      <td class="right_align cella_dati">{{totali.articoli}}</td>
    </tr>
    <tr>
      <th class="left_align titolo_dati">Q.<sup><u>tà</u></sup> richiesta</th>
      <td class="right_align cella_dati">{{qta_richiesta}}</td>
      <th class="left_align titolo_dati">Q.<sup><u>tà</u></sup> letta</th>
      <td class="right_align cella_dati">{{tot_pezzi}}</td>
    </tr>
    <tr>
      <th class="left_align tab_magazzino_ok">Ok</th>
      <td class="right_align tab_magazzino_ok">{{totali.ok}}</td>
      <th class="left_align tab_magazzino_some">Parziale</th>
      <td class="right_align tab_magazzino_some">{{totali.some}}</td>
    </tr>
    <tr>
      <th class="left_align tab_magazzino_more">Eccedenza</th>
      <td class="right_align tab_magazzino_more">{{totali.more}}</td>
      <th class="left_align tab_magazzino_unknown">Sconosciuto</th>
      <td class="right_align tab_magazzino_unknown">{{totali.unknown}}</td>
    </tr>
    <tr>
      <th class="left_align tab_magazzino_missing">Mancante</th>
      <td class="right_align tab_magazzino_missing">{{totali.missing}}</td>
      <th class="left_align tab_magazzino_not_requested">Non richiesto</th>
      <td class="right_align tab_magazzino_not_requested">{{totali.not_requested}}</td>
    </tr>
    <tr>
      <th class="left_align tab_magazzino_missing_giacenza">Non disponibili</th>
      <td class="right_align tab_magazzino_missing_giacenza">{{totali.missing_giacenza}}</td>
    </tr>
  </tbody>
</table>


  {% if not lettura_ok and tot_pezzi > 0 %}
  {% if operazione.ordine.richiesta_modificata %}
  {% else %}
  <ul class="errorlist"><li>Impossibile proseguire. Correggere gli errori nella lettura</li></ul>
  {% endif %}
  {% endif %}

  {% if verifica or completata %}
  <table class="tabella">
    <tr>
      <th>Produttore</th>
      <th>Barcode</th>
      <th>Codice Articolo</th>
      <th>Descrizione</th>
      <th>Quantità</th>
      <th>Quantità Richiesta</th>
      <th>Ubicazione</th>
    </tr>
    {% for v in verifica %}
    <tr class="tab_magazzino_{{v.res}}">
      <td>{{v.articolo.produttore}}</td>
      <td>{{v.codice_ean|safe}}</td>
      <td>{{v.articolo.codice}}</td>
      <td>{{v.articolo.descrizione}}</td>
      <td class="right_align">{{v.quantita}}</td>
      <td class="right_align">{{v.richiesta}}</td>
      <td class="right_align">{% for k, qta in v.ubicazioni.iteritems %}{{k|default:'N/A'}}<br/>{{qta}}{%if not forloop.last%}<br/>{%endif%}{% endfor%}</td>
      {% if v.ubicazione %}<td class="right_align">{{v.ubicazione}}</td>{% endif %}
    </tr>
    {% endfor %}

  <table>
  {% endif %}

</div>
{% endblock %}

src/agata/apps/magazzino/templates/magazzino/operazione_magazzino_ubicazioni.html
{% extends "magazzino/base_magazzino.html" %}

{% block content %}
<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
<script>
function verificaForm() {
  if ( $('#id_ubicazione').val() == '' ) {
    alert('Inserire l\'ubicazione');
    return false;
  }
  $('#form-magazzino').submit();
}
</script>
<h1>{{operazione|capfirst}} con ubicazioni</h1>
<div>

  <form action="{% url 'operazione_magazzino_ubicazioni' operazione %}" method="post" enctype="multipart/form-data" style="width:385px;" id="form-magazzino">{% csrf_token %}
    <table>
      <tr>
        <th>Magazzino</th>
        <th>Codice Articolo</th>
        <th>Quantità</th>
        <th>Ubicazione</th>
        <th>Note</th>
      </tr>
      <tr>
        <td>
          {{form.magazzino}}
          {{form.magazzino.errors}}
        </td>
        <td>
          {{form.codice_articolo}}
          {{form.codice_articolo.errors}}
        </td>
        <td>
          {{form.quantita}}
          {{form.quantita.errors}}
        </td>
        <td>
          {{form.ubicazione}}
          {{form.ubicazione.errors}}
        </td>
        <td>
          {{form.note}}
          {{form.note.errors}}
        </td>

        <td>
          <input type="button" value="{{operazione}}" onclick="verificaForm();"/>
        </td>
      </tr>
    </table>


  {% if msg %}
    <p class="{{msg_class}}">{{msg|safe}}</p>
  {% endif %}

  {% if lettura_ok %}
    <input type="hidden" value="{{lettura_ok}}" name="completa"/>
  {% endif %}

  </form>


</div>
{% endblock %}

src/agata/apps/magazzino/templates/magazzino/stampa_etichette.html
{% extends "magazzino/base_magazzino.html" %}


{% block content %}
<style>
textarea {
         height: 300px;
}
a.bottone {
display:block;
float:right;
width:140px;
height:40px;
    background:#979797;
}

a.bottone:hover {
    background:#D2E8D7;
}
</style>
<h1>Stampa etichette</h1>
<div>
  <form action="{% url 'magazzino_stampa_etichette' %}" method="post" enctype="multipart/form-data" style="width:385px;" id="profilo">{% csrf_token %}
    <table>
      <tr valign="top">
        <td>
          <label for="id_barcode">Barcode:</label>
          <input type="text" name="barcode" value="{{barcode}}"/>
        </td>
        <td>
          <label for="id_numero_etichette">Numero etichette:</label>
          <input type="text" name="numero_etichette" value="{{numero_etichette}}"/>
        </td>
        <td>
          <label for="id_offset">Offset:</label>
          <input type="text" name="offset" value="{{offset|default:0}}"/>
        </td>
      </tr>
      <tr>
	<td><input type="submit" value="Stampa" /></td>
	
      </tr>
    </table>

  </form>
{% endblock %}

src/agata/apps/magazzino/templates/magazzino/storico_articoli.html
{% extends "magazzino/base_magazzino.html" %}


{% block content %}
<style>
textarea {
         height: 300px;
}
a.bottone {
display:block;
float:right;
width:140px;
height:40px;
    background:#979797;
}

a.bottone:hover {
    background:#D2E8D7;
}
</style>
<h1>Storico articoli</h1>
<div>
	{% if elenco %}
	  <a class="bottone" href="{% url 'magazzino_storico_articoli_download' codice %}"><img src="/static/common/img/btn-download.png" alt="Download XLS"></a>
	{% endif %}

  <form action="{% url 'magazzino_storico_articoli' %}" method="post" enctype="multipart/form-data" style="width:385px;" id="profilo">{% csrf_token %}
    <table>
      <tr valign="top">
	<!--td>
	  <label for="id_cliente">Cliente: &nbsp;&nbsp;&nbsp;&nbsp;</label>
	  <select name="cliente" id="cliente">
	    {% for c in clienti %}
	    <option value="{{c.id}}" {%if id_cliente == c.id %}selected="selected"{% endif %}>{{c.ragione_sociale}}</option>
	    {% endfor %}
	  </select>
	</td-->
        <td>
          <label for="id_magazzino">Codice articolo:</label>
          <input type="text" name="codice" value="{{codice}}"/>
        </td>
	<td><input type="submit" value="Ricerca operazioni" /></td>

      </tr>


    </table>

    
  </form>



  {% if elenco %}
  <table class="tabella">
    <tr>
      <th>Data operazione</th>
      <th>Tipo operazione</th>
      <th>Magazzino Ingresso</th>
      <th>Magazzino Uscita</th>
      <th>Codice Articolo</th>
      <th>Quantità</th>
      <th>Note</th>
    </tr>
    {% for e in elenco %}
    <tr class="tab_magazzino_{{v.res}}">
      <td>{{e.0}}</td>
      <td>{{e.1}}</td>
      <td>{% if e.2 %}{{e.2}}{%endif%}</td>
      <td>{% if e.3 %}{{e.3}}{%endif%}</td>
      <td>{{e.4}}</td>
      <td>{{e.5}}</td>
      <td>{{e.6}}</td>
    </tr>
    {% endfor %}
  <table>

   {% if giacenze %}
   <h1 style="margin-top:20px;">Giacenze attuali</h1>
  <table class="tabella">
    <tr>
      <th>Magazzino</th>
      <th>Produttore</th>
      <th>Articolo</th>
      <th>Barcode</th>
      <th>Descrizione</th>
      <th>Giacenza</th>
    </tr>
    {% for e in giacenze %}
    <tr class="tab_magazzino_{{v.res}}">
      <td>{{e.magazzino}}</td>
      <td>{{e.articolo.produttore}}</td>
      <td>{{e.articolo.codice}}</td>
      <td>{{e.articolo.codice_ean}}</td>
      <td>{{e.articolo.descrizione}}</td>
      <td>{{e.quantita}}</td>
    </tr>
    {% endfor %}
  <table>

  {% endif %}
  {% endif %}

</div>
{% endblock %}